name: flutter_rounded_textbox
description: Draws text with a rounded box (contour) around it
version: 0.0.1
repository: https://github.com/daem-on/flutter_rounded_textbox

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

